table 'Strava Activities'
	lineageTag: c0539d43-842e-4e3a-9f07-30bc380374ae

	column name
		dataType: string
		lineageTag: 27c85eb5-078c-4d65-b262-e13f93e088c3
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column total_elevation_gain
		dataType: double
		lineageTag: e5ca49e7-7e89-4397-9903-4f58e722d89b
		summarizeBy: sum
		sourceColumn: total_elevation_gain

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id
		dataType: int64
		formatString: 0
		lineageTag: 84db17ea-559f-4b58-b19c-4a8f12f0d8fd
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d81c86a8-e69a-4975-ba0f-1b58db34381d
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: e879971c-d0e6-4d0f-9b37-377631422e14
			defaultHierarchy: LocalDateTable_34e7307d-4420-427d-8d7e-fb40ade7016c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column start_date_local
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ef7a56b-f2c7-43e9-b846-6267d686dc3b
		summarizeBy: none
		sourceColumn: start_date_local

		variation Variation
			isDefault
			relationship: 6e878994-a96e-43a9-9bc5-453c3c697f06
			defaultHierarchy: LocalDateTable_f916e506-4f59-4982-a58f-32e8274a9a02.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column timezone
		dataType: string
		lineageTag: 6fdb3de7-75ad-4ad8-bc59-e1e200b4cfeb
		summarizeBy: none
		sourceColumn: timezone

		annotation SummarizationSetBy = Automatic

	column utc_offset
		dataType: int64
		formatString: 0
		lineageTag: 5a45e8e9-9f97-4947-9592-15e0c50197ad
		summarizeBy: sum
		sourceColumn: utc_offset

		annotation SummarizationSetBy = Automatic

	column average_heartrate
		dataType: double
		lineageTag: c1b30b2d-eb5c-40d3-9770-f27e49cb25a7
		summarizeBy: sum
		sourceColumn: average_heartrate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_heartrate
		dataType: int64
		formatString: 0
		lineageTag: 9517dcea-7d72-4f9e-80ac-bdf73bd3c83a
		summarizeBy: sum
		sourceColumn: max_heartrate

		annotation SummarizationSetBy = Automatic

	column elev_high
		dataType: double
		lineageTag: b52f7518-4482-4b90-b211-e27a6cbe0429
		summarizeBy: sum
		sourceColumn: elev_high

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column elev_low
		dataType: double
		lineageTag: 4aa1eeef-51c5-4a79-bcfa-b54ac3c9c31e
		summarizeBy: sum
		sourceColumn: elev_low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column suffer_score
		dataType: int64
		formatString: 0
		lineageTag: 89d42c6c-db5d-4c8f-a5f3-85110a0a41c7
		summarizeBy: sum
		sourceColumn: suffer_score

		annotation SummarizationSetBy = Automatic

	column average_cadence
		dataType: double
		lineageTag: 319d93e7-9367-404c-97c2-e456499b51e4
		summarizeBy: sum
		sourceColumn: average_cadence

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column athlete_id
		dataType: int64
		formatString: 0
		lineageTag: 1cbd4b53-1ba6-4842-bb81-8f9ee0fd6b59
		summarizeBy: sum
		sourceColumn: athlete_id

		annotation SummarizationSetBy = Automatic

	column has_route
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 91634882-1362-4549-afdc-6bfc5ba81f5c
		summarizeBy: none
		sourceColumn: has_route

		annotation SummarizationSetBy = Automatic

	column start_lat
		dataType: double
		lineageTag: 756dc8f0-857d-482d-97a6-c605ec409a80
		summarizeBy: sum
		sourceColumn: start_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column start_lng
		dataType: double
		lineageTag: 1ca13040-40e6-4e7c-be2e-bf42d414cdfe
		summarizeBy: sum
		sourceColumn: start_lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column end_lat
		dataType: double
		lineageTag: c710daa5-5c62-4e1b-88a0-e7c3f7659a56
		summarizeBy: sum
		sourceColumn: end_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column end_lng
		dataType: double
		lineageTag: a3fa2bb5-7f5e-47fa-a56c-efab8e09607d
		summarizeBy: sum
		sourceColumn: end_lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column distance_km
		dataType: double
		lineageTag: d890c2b7-22ae-4062-8c64-44e6b721781b
		summarizeBy: sum
		sourceColumn: distance_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column moving_time_min
		dataType: double
		lineageTag: 85628253-7cc2-42f1-841e-602bddf7cc63
		summarizeBy: sum
		sourceColumn: moving_time_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column elapsed_time_min
		dataType: double
		lineageTag: afdb3024-63d9-41d7-b1df-ae9e75103b0e
		summarizeBy: sum
		sourceColumn: elapsed_time_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column average_speed_kmh
		dataType: double
		lineageTag: 2802c2d3-43cc-4362-bdb4-33c1af9b7f90
		summarizeBy: sum
		sourceColumn: average_speed_kmh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_speed_kmh
		dataType: double
		lineageTag: f4863d7a-8e30-4896-b9a6-fcd5ca594a5b
		summarizeBy: sum
		sourceColumn: max_speed_kmh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 03767001-8b2c-4eee-b574-7ede761091ce
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f3c8b548-4c3f-41d6-b9e5-514270b2cc7f
			defaultHierarchy: LocalDateTable_6a17051c-337f-4bdd-a23e-6826fdfcbf9f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 431db732-2e61-4298-9dd7-ed5ea01a7cb1
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 2195053e-577f-479f-a058-2ee66d3e2677
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 73854dee-b8d8-4d61-8471-39aeca7276be
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 839e0df2-5f5a-4f23-aa95-c18ef98739db
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 63c74c17-bdaa-479d-a75c-5355d5e0363b
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column hour_of_day
		dataType: int64
		formatString: 0
		lineageTag: d02f89e7-8eb1-4e2a-bcde-4a596f9d9a26
		summarizeBy: sum
		sourceColumn: hour_of_day

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 9e4c684f-41a9-4529-ba1a-eaf87cad8297
		summarizeBy: sum
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aaa27188-0efa-424f-9bc6-d982f396231d
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column time_of_day
		dataType: string
		lineageTag: 8c55bb86-ddf2-48a0-94c2-5f52bf962ce7
		summarizeBy: none
		sourceColumn: time_of_day

		annotation SummarizationSetBy = Automatic

	column pace_min_per_km
		dataType: double
		lineageTag: 74affd9a-7e2b-4222-9e35-2e4516a86cea
		summarizeBy: sum
		sourceColumn: pace_min_per_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_outdoor
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e58f078e-08e8-4921-a212-1e9f731a4f34
		summarizeBy: none
		sourceColumn: is_outdoor

		annotation SummarizationSetBy = Automatic

	column distance_bucket
		dataType: string
		lineageTag: c742f086-b606-41d1-a7d5-a17372d8488f
		summarizeBy: none
		sourceColumn: distance_bucket

		annotation SummarizationSetBy = Automatic

	column hr_zone
		dataType: string
		lineageTag: cbaebb89-d8cf-4fd3-8cbb-a80c825957a6
		summarizeBy: none
		sourceColumn: hr_zone

		annotation SummarizationSetBy = Automatic

	partition 'Strava Activities' = m
		mode: import
		source = ```
				let
				  Source = Csv.Document(
				    File.Contents(
				      "C:\Users\waleedmouhammed\OneDrive\Desktop\strava_project\Strava_Performance_Analysis\output\strava_activities.csv"
				    ), 
				    [Delimiter = ",", Columns = 68, Encoding = 65001, QuoteStyle = QuoteStyle.None]
				  ), 
				  PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]), 
				  ChangedType = Table.TransformColumnTypes(
				    PromotedHeaders, 
				    {
				      {"resource_state", Int64.Type}, 
				      {"name", type text}, 
				      {"total_elevation_gain", type number}, 
				      {"type", type text}, 
				      {"sport_type", type text}, 
				      {"workout_type", type text}, 
				      {"id", Int64.Type}, 
				      {"start_date", type datetime}, 
				      {"start_date_local", type datetime}, 
				      {"timezone", type text}, 
				      {"utc_offset", Int64.Type}, 
				      {"location_city", type text}, 
				      {"location_state", type text}, 
				      {"location_country", type text}, 
				      {"achievement_count", Int64.Type}, 
				      {"kudos_count", Int64.Type}, 
				      {"comment_count", Int64.Type}, 
				      {"athlete_count", Int64.Type}, 
				      {"photo_count", Int64.Type}, 
				      {"trainer", type logical}, 
				      {"commute", type logical}, 
				      {"manual", type logical}, 
				      {"private", type logical}, 
				      {"visibility", type text}, 
				      {"flagged", type logical}, 
				      {"gear_id", type text}, 
				      {"has_heartrate", type logical}, 
				      {"average_heartrate", type number}, 
				      {"max_heartrate", Int64.Type}, 
				      {"heartrate_opt_out", type logical}, 
				      {"display_hide_heartrate_option", type logical}, 
				      {"elev_high", type number}, 
				      {"elev_low", type number}, 
				      {"upload_id", Int64.Type}, 
				      {"upload_id_str", Int64.Type}, 
				      {"external_id", type text}, 
				      {"from_accepted_tag", type logical}, 
				      {"pr_count", Int64.Type}, 
				      {"total_photo_count", Int64.Type}, 
				      {"has_kudoed", type logical}, 
				      {"suffer_score", Int64.Type}, 
				      {"average_cadence", type number}, 
				      {"device_name", type text}, 
				      {"athlete_id", Int64.Type}, 
				      {"has_route", type logical}, 
				      {"start_lat", type number}, 
				      {"start_lng", type number}, 
				      {"end_lat", type number}, 
				      {"end_lng", type number}, 
				      {"distance_km", type number}, 
				      {"moving_time_min", type number}, 
				      {"elapsed_time_min", type number}, 
				      {"average_speed_kmh", type number}, 
				      {"max_speed_kmh", type number}, 
				      {"date", type date}, 
				      {"year", Int64.Type}, 
				      {"month", Int64.Type}, 
				      {"month_name", type text}, 
				      {"day_of_week", Int64.Type}, 
				      {"day_name", type text}, 
				      {"hour_of_day", Int64.Type}, 
				      {"week_of_year", Int64.Type}, 
				      {"is_weekend", type logical}, 
				      {"time_of_day", type text}, 
				      {"pace_min_per_km", type number}, 
				      {"is_outdoor", type logical}, 
				      {"distance_bucket", type text}, 
				      {"hr_zone", type text}
				    }
				  ), 
				  RemovedColumns = Table.RemoveColumns(
				    ChangedType, 
				    {
				      "resource_state", 
				      "type", 
				      "sport_type", 
				      "workout_type", 
				      "location_city", 
				      "location_state", 
				      "location_country", 
				      "achievement_count", 
				      "kudos_count", 
				      "comment_count", 
				      "athlete_count", 
				      "photo_count", 
				      "trainer", 
				      "commute", 
				      "manual", 
				      "private", 
				      "visibility", 
				      "flagged", 
				      "gear_id", 
				      "has_heartrate", 
				      "heartrate_opt_out", 
				      "display_hide_heartrate_option", 
				      "upload_id", 
				      "upload_id_str", 
				      "external_id", 
				      "from_accepted_tag", 
				      "pr_count", 
				      "total_photo_count", 
				      "has_kudoed", 
				      "device_name"
				    }
				  )
				in
				  RemovedColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

